### ISSUE TITLE
A tiny error in documentation

### ISSUE THREAD

**Issue by chenyangh** [PolyAI-LDN/conversational-datasets#37]
Thanks for sharing this code, and I am glad I have unused google cloud credits :)
Just found one tiny error while following the instructions of creating opensubtitles dataset

  --sentence_files gs://${BUCKET?}/opensubtitles/raw/lines-* \

====>

  --sentence_files gs://${BUCKET?}/opensubtitles/raw/lines/lines-* \

**Comment by chenyangh** [comment]
My mistake in closing the issue. I was trying to ask can I share the processed dataset? The processing of the three datasets cost me over 200 USD (credits) and the processing took almost a day (I could only use 69 instances in total), I think it would be better to just share the datasets directly.

**Comment by matthen** [comment]
thanks for reporting this, I have merged a PR to make your correction.
