### ISSUE TITLE
Using pytorch

### ISSUE THREAD

**Issue by vmurahari3** [PolyAI-LDN/conversational-datasets#48]
Was wondering if you any ideas on parsing these tf.Record files in pytorch?

**Comment by matthen** [comment]
What would be a more convenient data format? We could add support for something more generic, like  text files with json objects one per line

```
{'context/1': "Hello, how are you?", 'context/0': "I am fine. And you?", 'context': "Great. What do you think of the weather?", 'response': "It doesn't feel like February."}
{'context/0': "I am Matt", 'context': "Nice to meet you", 'response': "Nice to meet you too."}
```

**Comment by vmurahari3** [comment]
That would be so wonderful. Json files will be amazing :)

**Comment by matthen** [comment]
I introduced JSON format in this PR:

https://github.com/PolyAI-LDN/conversational-datasets/pull/49

Just run add `--dataset_format JSON` when calling `create_data.py`
