### ISSUE TITLE
Bad TF version in requirements file

### ISSUE THREAD

**Issue by theo-m** [PolyAI-LDN/conversational-datasets#50]
On using `pip install apache-beam==2.5.0` I'm getting:
```
ERROR: tensorflow 1.12.0 has requirement tensorboard<1.13.0,>=1.12.0, but you'll have tensorboard 1.13.1 which is incompatible.
```
I would assume the error comes from https://github.com/PolyAI-LDN/conversational-datasets/blob/6282739663fc8065085914b33d703436730be007/requirements.txt#L73

Will push a PR if we can confirm the issue.

**Comment by matthen** [comment]
Is this following the readme?

```
python2.7 -m virtualenv venv
. venv/bin/activate
pip install -r requirements.txt
```

the circle CI build should be testing that works correctly. maybe you are not using a fresh virtualenv?

**Comment by theo-m** [comment]
You're right, I was trusting PyCharm to handle the requirements and didn't check it defaulted to a conda environment. Testing with virtualenv.

**Comment by theo-m** [comment]
That was it, I'm surprised it would fail with a conda environment and not with a virtualenv one but it's not important. Thanks!

**Comment by matthen** [comment]
👍
